# Generated by Django 5.2.1 on 2025-05-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliants.agency'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_agency_admin',
            field=models.BooleanField(default=False),
        ),
    ]
