# Generated by Django 5.2.1 on 2025-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliants', '0002_user_agency_user_is_agency_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/'),
        ),
    ]
