# Generated by Django 5.2.1 on 2025-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliants', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
